
export const MonstersTypes = {
 REQUEST_MONSTERS_DATA_START = "REQUEST_MONSTERS_DATA_START";
 REQUEST_MONSTERS_DATA_SUCCESS = "REQUEST_MONSTERS_DATA_SUCCESS";
 REQUEST_MONSTERS_DATA_FAILURE = "REQUEST_MONSTERS_DATA_FAILURE";
}
